FROM python:3.12-slim

WORKDIR /app

# 复制依赖文件并安装
COPY requirements.txt .
RUN python3 -m pip install --no-cache-dir -r requirements.txt

# 复制应用代码
COPY . /app

# 设置环境变量
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

# 运行应用
ENTRYPOINT [ "python3", "-u", "main.py" ]
