DROP TABLE IF EXISTS mails;
DROP TABLE IF EXISTS address;
CREATE TABLE IF NOT EXISTS mails (id INTEGER PRIMARY KEY, address TEXT, message TEXT);
CREATE TABLE IF NOT EXISTS address (id INTEGER PRIMARY KEY, name TEXT UNIQUE);
