name: Upstream Sync

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Sync upstream changes
        run: gh repo sync ${{ github.repository }} --source dreamhunter2333/cloudflare_temp_email --branch main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
